# Test workflow to show how this feature works. DO NOT MERGE, REMOVE IN FINAL VERSION OF PR
name: Rector

on:
    push:

jobs:
    batch_rector:
        strategy:
            matrix:
                batches: [0, 1, 2, 3]

        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v4

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   run: composer install --no-progress --ansi

            -   run: bin/rector process --batch-index=${{ strategy.job-index }} --batch-total=${{ strategy.job-total }} --ansi

            -
                uses: EndBug/add-and-commit@v9
                with:
                    message: 'Rector Batch ${{ strategy.job-index }}'
                    author_name: 'GitHub Action <actions@github.com>'
                    author_email: 'action@github.com'
                    pull: '--autostash'
